# Generated by Django 2.2 on 2021-04-05 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto Generated and unique', verbose_name='UUID')),
                ('name', models.CharField(help_text='If you delete a category you will delete all the blog posts associated with this category. TAKE CARE', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, help_text='Auto generated and unique', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto Generated and unique', verbose_name='UUID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, help_text='Auto generated and unique', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('content', models.TextField(help_text='If you delete a category you will delete all the blog posts associated with this category. TAKE CARE', verbose_name='Content')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Category')),
            ],
        ),
    ]
