# Generated by Django 2.2 on 2021-03-23 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='programming', editable=False, help_text='Auto generated and unique', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto Generated and unique', verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='dodgy-slug', editable=False, help_text='Auto generated and unique', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto Generated and unique', verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='If you delete a category you will delete all the blog posts associated with this category. TAKE CARE', verbose_name='Content'),
        ),
    ]
